### ISSUE TITLE
Key mappings appear in random order

### ISSUE THREAD

**Issue by seancorfield** [joshuafcole/keymapper#8]
It would be easier to use if either they were sorted by the key or by the command.

**Comment by seancorfield** [comment]
Having experimented with both, I'm not sure which is going to be the most intuitive:

```
(defui keymap-list [this keys]
  [:ul.keymapper-list (map (partial keymap-item this) (sort-by (comp print-str second) keys))])
```

or:

```
(defui keymap-list [this keys]
  [:ul.keymapper-list (map (partial keymap-item this) (sort-by first keys))])
```

To sort on the commands you need to `print-str` them first since some are sequences and some are keywords, whereas all the keys seem to be strings.

Sorting by commands is interesting because it shows the alternative key mappings together for each command, but overall sorting by keys "looks" better to me.

**Comment by joshuafcole** [comment]
Sorry for the delayed response, no excuse here. I switched to gmail's priority inbox and at some point it decided to start hiding my github issues under forums instead of the primary. I think the best approach might be to let the end user choose the sort order in the same sense that rich tables tend to -- a sort ascending/descending button on each column label.
